### ISSUE TITLE
WiringPi no longer supported

### ISSUE THREAD

**Issue by GavinKane** [tomfclarke/adafruit-motor-hat-cpp-library#1]
WiringPi is required for this library.  However, the author of the WiringPi Library, Gordon, has stated that the WiringPi Library is now deprecated and presently the source code is not available for download or installation.  (As of 9. Aug 2019)
[http://wiringpi.com/wiringpi-deprecated/](http://wiringpi.com/wiringpi-deprecated/)
Is it possible to update the adafruit-motor-hat-cpp library to another i2c library?

**Comment by tomfclarke** [comment]
Thanks for letting me know @GavinKane. I was aware that Gordon had deprecated the library, but expected the final version of source to remain available. I'll take a look at alternatives as soon as I can!
