### ISSUE TITLE
Missing case "kbrake" in adafruitdcmotor.cpp

### ISSUE THREAD

**Issue by jonste99** [tomfclarke/adafruit-motor-hat-cpp-library#3]
In the header-file you defined a command enum in which you define the command "kbrake", but the case to run this command is missing in the following switch statement.
switch (command)
    {
        case kForward:
            setPin (in1Pin, true);
            setPin (in2Pin, false);
            break;
        case kBackward:
            setPin (in1Pin, false);
            setPin (in2Pin, true);
            break;
//Here needs to be the case for kbrake
        case kRelease:
            setPin (in1Pin, false);
            setPin (in2Pin, false);
            break;
        default:
            break;
    }

**Comment by tomfclarke** [comment]
Sorry for the delayed response! Thanks for pointing this out. I'll take a look today.
